# Generated by Django 4.1.3 on 2023-10-16 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_detallepedidoproveedor_pedidoproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('recibido', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='DetallePedidoProveedor',
        ),
        migrations.DeleteModel(
            name='PedidoProveedor',
        ),
    ]
