# Generated by Django 4.1.3 on 2023-10-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_detalleventa_venta_remove_factura_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
