# Generated by Django 4.1.3 on 2023-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_venta_cliente_delete_detalleventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patientfeedback',
            name='pharmacist_id',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminHOD'), (4, 'PharmacyClerk')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='Dispense',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
